name: Preprocessing Data

on:
  push:
    branches:
      - main  # atau sesuaikan branch kamu

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: |
          python automate_preprocessing.py --input data/raw_data.csv --output-dir preprocessing

      - name: Upload preprocessed data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: preprocessed-data
          path: preprocessing/
